baseurl: ""
url: https://blog.coderbyheart.com
lang: en
timezone: Europe/Berlin

harmony:
  name: coder::by(&lt;3); // blog
  description: by Markus Tacker, a CTO from Offenbach, Germany.
  photo: https://farm8.staticflickr.com/7336/13376420184_1f7c386fd7_n.jpg
  meta_description: > #
    Blog by Markus Tacker, a CTO from Offenbach, Germany.
    A coder by â™¥ and organizational hacker by passion.
    I help teams to build great software and to enjoy their work.
  basetheme: harmony
  author:
    name: Markus Tacker
    email: m@coderbyheart.com
    url: https://coderbyheart.com/
  social:
    github: coderbyheart
    twitter: coderbyheart
# disqus handle, leave blank to disable
disqus: coderbyheart

# Conversion / Build settings
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

google_site_verification: anJEIOoin7qq0c8P4s3ajkPz518xhhbYQvlpSg97-p8
